## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Generate Models
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

name: _xyz_generate_screen_access
version: 0.3.0
publish_to: none
environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'
dependency_overrides:
  analyzer: 5.10.0
  xyz_generate_screen_access_annotations:
    path: ../xyz_generate_screen_access_annotations/
  xyz_utils:
    path: ../../xyz_utils
dependencies:
  xyz_generate_screen_access_annotations:
    git:
      url: https://github.com/robmllze/xyz_generate_screen_access_annotations.git
      ref: master
  xyz_utils:
    git:
      url: https://github.com/robmllze/xyz_utils.git
      ref: master
  analyzer: 5.10.0
  build: 2.3.1
  glob: 2.1.1
  path: 1.8.3
  source_gen: 1.2.7
